### ISSUE TITLE
Create Raw Sketch for level 3

### ISSUE THREAD

**Issue by DebugAgrawal** [Open-Sourced-Olaf/Olafs-Adventure#5]

**Comment by YuanSamuel** [comment]
![Level 3 Sketch Part 1](https://user-images.githubusercontent.com/37784817/110814439-0f8f2a00-824f-11eb-9c09-e0749d2e8150.jpg)

![Level 3 Sketch Part 2](https://user-images.githubusercontent.com/37784817/110814548-29307180-824f-11eb-8303-bd434eb5cb18.jpg)
